AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Assessly - AI GitHub Assessment Reviewer

# --- PARAMETERS
Parameters:
  Stage:
    Type: String
    Description: stage name for all resources
    AllowedValues:
      - dev
      - prod
    Default: dev

# --- GLOBALS
Globals:
  Function:
    Runtime: nodejs24.x
    Architectures:
      - arm64
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  # --- LAMBDA FUNCTIONS
  # Trigger Function
  TriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambdas/analyze-trigger.handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ProcessQueue.QueueName
      Environment:
        Variables:
          QUEUE_URL: !Ref ProcessQueue
      Events:
        AnalyzeApi:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /analyze
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        External:
          - '@aws-sdk/*'
        Sourcemap: true
        EntryPoints:
          - src/lambdas/analyze-trigger.ts

  #  Actual Processing Function
  ProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambdas/analyze-process.handler
      Timeout: 300
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DATABASE_URL: !Sub "{{resolve:ssm:/assessly/${Stage}/DATABASE_URL}}"
          GITHUB_TOKEN: !Sub "{{resolve:ssm:/assessly/${Stage}/GITHUB_TOKEN}}"
          OPENAI_API_KEY: !Sub "{{resolve:ssm:/assessly/${Stage}/OPENAI_API_KEY}}"
      Events:
        ProcessQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessQueue.Arn
            BatchSize: 1
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        External:
          - '@aws-sdk/*'
          - '@prisma/client'
          - '.prisma'
        Sourcemap: true
        EntryPoints:
          - src/lambdas/analyze-process.ts

  # Get Assessment Function
  GetAssessmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/lambdas/get-assessment.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DATABASE_URL: !Sub "{{resolve:ssm:/assessly/${Stage}/DATABASE_URL}}"  
      Events:
        GetAssessmentApi:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /assessment/{id}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2022
        External:
          - '@aws-sdk/*'
          - '@prisma/client'
          - '.prisma'
        Sourcemap: true
        EntryPoints:
          - src/lambdas/get-assessment.ts

  # --- LOG GROUPS
  LogGroup1:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub '/aws/lambda/${TriggerFunction}'
      RetentionInDays: 3

  LogGroup2:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProcessFunction}'
      RetentionInDays: 3

  LogGroup3:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub '/aws/lambda/${GetAssessmentFunction}'
      RetentionInDays: 3

  # --- SQS QUEUE
  ProcessQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300
      QueueName: !Sub "${Stage}-AssesslyProcessQueue"

  # --- API GATEWAY
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowMethods: "'GET,POST,OPTIONS'"

Outputs:
  AssesslyApi:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
